### ISSUE TITLE
blank lines in `package` docstring don't seem to translate to carriage return in generated output

### ISSUE THREAD

**Issue by gmabey** [markvincze/sabledocs#18]
Some basic markdown-esque features seems to be working, such as inserting a blank line where a new paragraph is desired.

This seems to work great in regular message docstrings, but doesn't seem to work for `package` docstring. (all of the content seems to go into a single paragraph)

**Comment by markvincze** [comment]
@gmabey  Thanks for reporting this, good catch!

Should be fixed in #24

**Comment by markvincze** [comment]
Fixed in #24  
@gmabey if you can also test if it works now correctly, that'd be appreciated!

**Comment by markvincze** [comment]
@gmabey Closing this now, feel free to reply if it's still not working correctly.

**Comment by gmabey** [comment]
Yes! it does work thank you.
