### ISSUE TITLE
Run in CI

### ISSUE THREAD

**Issue by arvkonstantin** [markvincze/sabledocs#22]
It would be great if it turned out to prepare a docker image that has both protoc and sabledocs for the possibility of generating from CI jobs.

**Comment by markvincze** [comment]
@arvkonstantin I created a docker image: https://hub.docker.com/r/markvincze/sabledocs, it gets published on every CI build.

Can you check if this would work for you?

**Comment by markvincze** [comment]
@arvkonstantin I'm closing this now, feel free to reply if it's not working as expected.

(Currently there is just one variant of the image, the full one, I'm still planning to add some of the usual variants, like `-slim` and `-alpine`.)
