### ISSUE TITLE
Search bar can't find message names

### ISSUE THREAD

**Issue by soleilankerbaril** [markvincze/sabledocs#39]
When searching for a message name, no results are found

Here is the existing message:
![image](https://github.com/markvincze/sabledocs/assets/33331748/0ccb6b5f-fc55-4ece-86b0-87600a11a06d)

Here is the search input:
![image](https://github.com/markvincze/sabledocs/assets/33331748/0a76994a-fce6-4f2b-8917-0aa037860ad7)

Here is the search result:
![image](https://github.com/markvincze/sabledocs/assets/33331748/ed32bfdd-9dc3-4e1e-82b6-c34d71a8998e)

**Comment by markvincze** [comment]
Thanks for creating the issue with a detailed example!

I remember Lunr search was a bit tricky to configure correctly, and I tried testing it thoroughly at the time, but something might've changed since then, I'll investigate why the message name is not working as the search term.

**Comment by markvincze** [comment]
@soleilankerbaril , this seems to be related to case sensitivity.

To confirm: if you search for lowercase "contextsconfig", do you get the search result then?

**Comment by markvincze** [comment]
@soleilankerbaril Attempted to fix in #43, it's released as a prerelease version: https://pypi.org/project/sabledocs/0.11.541.dev0/, if you could give it a try to see if it fixes the issue, that'd be appreciated!

**Comment by soleilankerbaril** [comment]
Hi, Thanks for the quick fix. 
I confirm that it wasn't a case-sensitive issue, since it did not work with upper case or lower case.

The fix works perfect, thank you. I am now able to search for messages, and it is not case-sensitive as bonus 😉

PS: Love the work you did with this doc generator.

**Comment by markvincze** [comment]
@soleilankerbaril Right, there was another issue, that the full type name was not split per `.` during the indexing, so if you had a type `Person` in package `foo.bar`, then only searching for "foo.bar.person" was working, "person" was not, probably you were hitting this issue as well 🙂. That's also fixed now.

Thanks, I'm glad that you like it! I'll merge the PR so the fix will be released in the next stable version.

**Comment by soleilankerbaril** [comment]
Cool, thanks. Should I close this issue or are you going to close it with when the next stable version comes out?

**Comment by markvincze** [comment]
@soleilankerbaril The fix was released to stable, closing this now.
